### PR TITLE
Followed linting rules by Lint package

### PR DESCRIPTION
**Pull request by YDA93**
Applied all the rules.

### CODE REVIEW

**Comment by apgapg** [comment]
Thank you for this PR. This refactor was much needed

**Review by apgapg — APPROVED** [review]
LGTM

**Comment by apgapg** [comment]
@YDA93 which command or package did you use for this refactor?

**Comment by YDA93** [comment]
> @YDA93 which command or package did you use for this refactor?

I used https://pub.dev/packages/lint

Your welcome!

**Pull request merged**
